# Site settings
title: The Nashville Transparency Project
email: your-email@domain.com
description: The Nashville Transparency Project serves to provide active citizenship in the metropolitan area.
baseurl: ""
url: "http://www.nashvilletransparencyproject.org" # the base hostname & protocol for your site
twitter_username: ntp
github_username:  code-for-nashville

# Build settings
markdown: kramdown
